name: check

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Fetch Release Version
        run: |
          wget -qO- -t3 -T10 --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          "https://api.github.com/repos/SpiderLabs/ModSecurity/releases/latest" \
          | grep '"tag_name"' \
          | head -n 1 | awk -F "\"" '{print $4}' > VERSION

      - name: Check for Modified Files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Setup GPG Private Key
        if: steps.git-check.outputs.modified == 'true'
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false

      - name: Commit Latest Release Version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Luke Wang'
          git config --global user.email '44051798+0v0-plus@users.noreply.github.com'
          git add .
          git commit -m "fetch upstream release version"
          git tag $(cat VERSION)
          git push
          git push origin $(cat VERSION)
